
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://hwziukmxpmddsknqhfxn.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3eml1a214cG1kZHNrbnFoZnhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMTk0NjQsImV4cCI6MjA2NTY5NTQ2NH0.oHYsJmqMNQRSPxsWB0Yw-6QcWU_n7nvllG_A7R-0uko';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
